### ISSUE TITLE
Elements are not appearing on the page after a log-in attempt

### ISSUE THREAD

**Issue by kirillian** [charlottejuniordevs/api#4]
@binarymason mentioned that this is probably due to an authentication issue, but certain elements like the user's avatar and the repos are not showing up after a user logs in. Refreshing the page is a work-around for now.

**Comment by binarymason** [comment]
https://github.com/charlottejuniordevs/client/commit/4d25d4ee91d7450dc8b5f8d2356cba8ab99e3e19 should have fixed this. 👍
