### ISSUE TITLE
The favicon for the site is the React favicon

### ISSUE THREAD

**Issue by kirillian** [charlottejuniordevs/api#5]

**Comment by kirillian** [comment]
The favicon for the site should probably be the Charlotte Junior Devs logo.

**Comment by kirillian** [comment]
This issue is the same as this one in the client repo:
https://github.com/charlottejuniordevs/client/issues/21

Closing this issue in lieu of that one as it seems more appropriate.

**Comment by binarymason** [comment]
Yeah, front end stuff goes in https://github.com/charlottejuniordevs/client 👍
